image: Visual Studio 2019

environment:
  matrix:
  - PLATFORM: x86
  - PLATFORM: x64

before_build:
  - appveyor DownloadFile https://libsdl.org/release/SDL2-devel-2.0.10-VC.zip
  - 7z x SDL2-devel-2.0.10-VC.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%/SDL2-2.0.10/;%APPVEYOR_BUILD_FOLDER%/SDL2-2.0.10/include;%PATH%
  - if %PLATFORM% == x86 set PATH=%APPVEYOR_BUILD_FOLDER%/SDL2-2.0.10/lib/x86;%PATH%
  - if %PLATFORM% == x64 set PATH=%APPVEYOR_BUILD_FOLDER%/SDL2-2.0.10/lib/x64;%PATH%
  - echo set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/") > SDL2-2.0.10\sdl2-config.cmake
  - echo if (${CMAKE_SIZEOF_VOID_P} MATCHES 8) >> SDL2-2.0.10\sdl2-config.cmake
  - echo   set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2main.lib") >> SDL2-2.0.10\sdl2-config.cmake
  - echo else () >> SDL2-2.0.10\sdl2-config.cmake
  - echo   set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2main.lib") >> SDL2-2.0.10\sdl2-config.cmake
  - echo endif () >> SDL2-2.0.10\sdl2-config.cmake
  - echo string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES) >> SDL2-2.0.10\sdl2-config.cmake

build_script:
  - mkdir build
  - cd build
  - if %PLATFORM% == x86 cmake .. -G "Visual Studio 16 2019" -A Win32
  - if %PLATFORM% == x64 cmake .. -G "Visual Studio 16 2019" -A x64
  - cmake --build .
